services:
  rust:
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
      - rust-target:/workspace/target
    env_file:
      - .env
    ports:
      - 8000:8000

volumes:
  rust-target:
